# Generated by Django 4.0.6 on 2022-08-05 07:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateField(auto_created=True, default=users.models.get_default_date),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
