# Generated by Django 4.1.2 on 2022-10-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_categories_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
