# Generated by Django 4.1.2 on 2022-10-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_product_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='code',
        ),
    ]
